var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.polyfill=function(a,b,d,c){if(b){d=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var e=a[c];e in d||(d[e]={});d=d[e]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("Array.from",function(a){return a?a:function(a,d,c){$jscomp.initSymbolIterator();d=null!=d?d:function(a){return a};var b=[],h=a[Symbol.iterator];if("function"==typeof h){a=h.call(a);for(var f=0;!(h=a.next()).done;)b.push(d.call(c,h.value,f++))}else for(h=a.length,f=0;f<h;f++)b.push(d.call(c,a[f],f));return b}},"es6","es3");
$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},b=Object.create(new $jscomp.global.Proxy(a,{get:function(d,c,e){return d==a&&"q"==c&&e==b}}));return!0===b.q}catch(d){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.polyfill("WeakMap",function(a){function b(){if(!a||!Object.seal)return!1;try{var c=Object.seal({}),g=Object.seal({}),b=new a([[c,2],[g,3]]);if(2!=b.get(c)||3!=b.get(g))return!1;b.delete(c);b.set(g,4);return!b.has(c)&&4==b.get(g)}catch(l){return!1}}function d(a){$jscomp.owns(a,e)||$jscomp.defineProperty(a,e,{value:{}})}function c(a){var g=Object[a];g&&(Object[a]=function(a){d(a);return g(a)})}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;
var e="$jscomp_hidden_"+Math.random();c("freeze");c("preventExtensions");c("seal");var h=0,f=function(a){this.id_=(h+=Math.random()+1).toString();if(a){$jscomp.initSymbol();$jscomp.initSymbolIterator();a=$jscomp.makeIterator(a);for(var g;!(g=a.next()).done;)g=g.value,this.set(g[0],g[1])}};f.prototype.set=function(a,g){d(a);if(!$jscomp.owns(a,e))throw Error("WeakMap key fail: "+a);a[e][this.id_]=g;return this};f.prototype.get=function(a){return $jscomp.owns(a,e)?a[e][this.id_]:void 0};f.prototype.has=
function(a){return $jscomp.owns(a,e)&&$jscomp.owns(a[e],this.id_)};f.prototype.delete=function(a){return $jscomp.owns(a,e)&&$jscomp.owns(a[e],this.id_)?delete a[e][this.id_]:!1};return f},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var g=Object.seal({x:4}),b=new a($jscomp.makeIterator([[g,"s"]]));if("s"!=b.get(g)||1!=b.size||b.get({x:4})||b.set({x:4},"t")!=b||2!=b.size)return!1;var c=b.entries(),d=c.next();if(d.done||d.value[0]!=g||"s"!=d.value[1])return!1;d=c.next();return d.done||4!=d.value[0].x||"t"!=d.value[1]||!c.next().done?!1:!0}catch(m){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;$jscomp.initSymbol();$jscomp.initSymbolIterator();var d=new WeakMap,c=function(a){this.data_={};this.head_=f();this.size=0;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};c.prototype.set=function(a,b){a=0===a?0:a;var c=e(this,a);c.list||(c.list=this.data_[c.id]=[]);c.entry?c.entry.value=b:(c.entry={next:this.head_,previous:this.head_.previous,head:this.head_,
key:a,value:b},c.list.push(c.entry),this.head_.previous.next=c.entry,this.head_.previous=c.entry,this.size++);return this};c.prototype.delete=function(a){a=e(this,a);return a.entry&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.data_[a.id],a.entry.previous.next=a.entry.next,a.entry.next.previous=a.entry.previous,a.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=f();this.size=0};c.prototype.has=function(a){return!!e(this,a).entry};
c.prototype.get=function(a){return(a=e(this,a).entry)&&a.value};c.prototype.entries=function(){return h(this,function(a){return[a.key,a.value]})};c.prototype.keys=function(){return h(this,function(a){return a.key})};c.prototype.values=function(){return h(this,function(a){return a.value})};c.prototype.forEach=function(a,b){for(var c=this.entries(),d;!(d=c.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var e=function(a,b){var c=b&&typeof b;"object"==
c||"function"==c?d.has(b)?c=d.get(b):(c=""+ ++k,d.set(b,c)):c="p_"+b;var e=a.data_[c];if(e&&$jscomp.owns(a.data_,c))for(a=0;a<e.length;a++){var f=e[a];if(b!==b&&f.key!==f.key||b===f.key)return{id:c,list:e,index:a,entry:f}}return{id:c,list:e,index:-1,entry:void 0}},h=function(a,b){var c=a.head_;return $jscomp.iteratorPrototype(function(){if(c){for(;c.head!=a.head_;)c=c.previous;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})},f=function(){var a={};return a.previous=
a.next=a.head=a},k=0;return c},"es6","es3");
$jscomp.polyfill("Set",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_SET||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),b=new a($jscomp.makeIterator([c]));if(!b.has(c)||1!=b.size||b.add(c)!=b||1!=b.size||b.add({x:4})!=b||2!=b.size)return!1;var d=b.entries(),f=d.next();if(f.done||f.value[0]!=c||f.value[1]!=c)return!1;f=d.next();return f.done||f.value[0]==c||4!=f.value[0].x||f.value[1]!=f.value[0]?!1:d.next().done}catch(k){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;$jscomp.initSymbol();$jscomp.initSymbolIterator();var d=function(a){this.map_=new Map;if(a){a=$jscomp.makeIterator(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.map_.size};d.prototype.add=function(a){a=0===a?0:a;this.map_.set(a,a);this.size=this.map_.size;return this};d.prototype.delete=function(a){a=this.map_.delete(a);this.size=this.map_.size;return a};d.prototype.clear=
function(){this.map_.clear();this.size=0};d.prototype.has=function(a){return this.map_.has(a)};d.prototype.entries=function(){return this.map_.entries()};d.prototype.values=function(){return this.map_.values()};d.prototype.keys=d.prototype.values;d.prototype[Symbol.iterator]=d.prototype.values;d.prototype.forEach=function(a,b){var c=this;this.map_.forEach(function(d){return a.call(b,d,d,c)})};return d},"es6","es3");
Array.prototype.transpose||(Array.prototype.transpose=function(){var a=this.length?this.length:0,b=this[0]instanceof Array?this[0].length:0;if(0===b||0===a)return[];var d,c,e=[];for(d=0;d<b;d++)for(e[d]=[],c=0;c<a;c++)e[d][c]=this[c][d];return e});Array.prototype.move||(Array.prototype.move=function(a,b){if(b>=this.length)for(var d=b-this.length;d--+1;)this.push(void 0);this.splice(b,0,this.splice(a,1)[0]);return this});
Array.prototype.remove||(Array.prototype.remove=function(){for(var a=0;a<arguments.length;a++){var b=arguments[a];if("object"===typeof b&&"length"in b)for(var d=0;d<b.length;d++)this.remove(b[d]);else{var c;-1!==(c=this.indexOf(b))&&this.splice(c,1)}}return this});Array.prototype.intersect||(Array.prototype.intersect=function(a){"object"!==typeof a&&(a=Array.from(arguments));return this.filter(function(b){return-1!==a.indexOf(b)})});
Array.prototype.union||(Array.prototype.union=function(){for(var a=0;a<arguments.length;a++){var b=arguments[a];if("object"===typeof b&&"length"in b)for(var d=0;d<b.length;d++)this.merge(b[d]);else-1===this.indexOf(b)&&this.push(b)}return this});Array.prototype.merge||(Array.prototype.merge=Array.prototype.union);
Array.prototype.containsArray||(Array.prototype.containsArray=function(){for(var a=0;a<arguments.length;a++){var b=arguments[a];if("object"===typeof b&&"length"in b)for(var d=0;d<b.length;d++){if(-1===this.indexOf(b[d]))return!1}else if(-1===this.indexOf(b))return!1}return!0});Array.prototype.includesArray||(Array.prototype.includesArray=Array.prototype.containsArray);
Array.prototype.clean||(Array.prototype.clean=function(){for(var a=this.length-1;0<=a;a--)if(arguments.length)for(var b=0;b<arguments.length;b++)this[a]===arguments[b]&&this.splice(a,1);else this[a]||this.splice(a,1);return this});Array.prototype.unique||(Array.prototype.unique=function(){return Array.from(new Set(this))});
