var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.arrayIterator=function(a){var b=0;return $jscomp.iteratorPrototype(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();$jscomp.initSymbol();$jscomp.initSymbolIterator();var b=a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.checkStringArgs=function(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};
$jscomp.polyfill("String.prototype.startsWith",function(a){return a?a:function(a,c){var b=$jscomp.checkStringArgs(this,a,"startsWith");a+="";var e=b.length,f=a.length;c=Math.max(0,Math.min(c|0,b.length));for(var g=0;g<f&&c<e;)if(b[c++]!=a[g++])return!1;return g>=f}},"es6","es3");$jscomp.polyfill("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}},"es6","es3");
$jscomp.polyfill("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var e=b.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=b[c];if(f===a||Object.is(f,a))return!0}return!1}},"es7","es3");$jscomp.polyfill("String.prototype.includes",function(a){return a?a:function(a,c){return-1!==$jscomp.checkStringArgs(this,a,"includes").indexOf(a,c||0)}},"es6","es3");
function flatten(a){return a.reduce(function(a,c){return a.concat(Array.isArray(c)?flatten(c):c)},[])}function isdigit(a){return"0"<=a&&"9">=a}function isNumber(a){return!isNaN(parseFloat(a))&&isFinite(a)}function MakeID(a){return"undefined"==typeof a||null==a?null:a.replace(/[^a-zA-Z\d\-_]/g,"_")}function escapeRegExp(a){return a.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&")}Slick.definePseudo("visible",function(){return"hidden"!=this.getStyle("visibility")&&this.isVisible()&&this.isDisplayed()});
Slick.definePseudo("enabled",function(){return!this.hasClass("disabled")});Slick.definePseudo("match",function(a){a=a||"";var b=this.innerHTML.replace(/&lt;/g,"<").replace(/&gt;/g,">");return a==b||(new RegExp("^"+a+"$")).test(b)});function pagename(a){return a.replace(/^.*\/|\.[^.]*$/g,"")}
function ajax(a,b){var c="undefined"!==typeof b,d;(new Request.JSON({url:"server.php",method:"POST",async:c,data:a,onRequest:function(){document.body.setStyle("cursor","wait")},onSuccess:function(a){c?b(a):d=a},onError:function(b){console.log("server request failure.",a);"function"==typeof Error&&Error("server request failure."+a)},onComplete:function(){document.body.setStyle("cursor","auto")}})).send();if(!c)return d}
function get(a){var b;(new Request({url:a,method:"get",async:!1,onSuccess:function(a){b=a}})).send();return b}function GetFieldValue(a){a=$(MakeID(a));return GetElementValue(a)}function SetFieldValue(a,b){a=$(MakeID(a));SetElementValue(a,b)}
function GetElementValue(a){if(!a)return null;var b=a.get("tag");"input"==b&&(b=a.get("type"));switch(b){case "checkbox":return a.checked?1:0;case "label":return a.get("text");case "date":return a.value?(new Date(a.value)).format("mm/dd/yyyy",!0):null;case "div":case "span":case "td":return a.get("text");default:return a.value}}
function SetElementValue(a,b){if(a){var c=a.get("tag");"input"==c&&(c=a.get("type"));switch(c){case "select":c=!1;for(var d=0;d<a.options.length;d++)if(a.options[d].value==b){c=!0;break}c||(c=document.createElement("option"),c.value=b,a.add(c));a.set("value",b);break;case "span":a.set("text",b);break;case "checkbox":a.set("checked",+b);break;case "text":a.set("value",b);break;case "date":a.set("value",b?(new Date(b)).format("yyyy-mm-dd",!0):"");break;case "label":a.set("text",b);break;default:a.set("text",
b)}}}function GetColumnHeaderFromFieldName(a){return"number"==typeof a?a:a in _SAMPLE?GetLabelForDisplay(a,_SAMPLE[a]):a}function GetFieldNameFromColumnHeader(a){for(var b in _SAMPLE)if(GetLabelForDisplay(b,_SAMPLE[b])==a)return b;return a}function GridRow(a){return _GRID.row(a)}function GridCell(a,b){return _GRID.cell(a,GetColumnHeaderFromFieldName(b))}function GridGetText(a,b){return _GRID.getText(a,GetColumnHeaderFromFieldName(b))}
function GridGetCell(a,b){return _GRID.getCell(a,GetColumnHeaderFromFieldName(b))}function GridSetCell(a,b,c,d,e,f,g){return _GRID.setCell(a,GetColumnHeaderFromFieldName(b),c,d,e,f,g)}
function FastTable(a,b){var c=[];c.push('<table id="grid">');c.push("<thead>");c.push("<tr>");for(var d=0;d<a.length;d++)c.push("<th>"),c.push(a[d]),c.push("</th>");c.push("</tr>");c.push("</thead>");c.push("<tbody>");for(a=0;a<b.length;a++){c.push("<tr>");d=b[a];for(var e=0;e<d.length;e++)c.push("<td>"),c.push(d[e]),c.push("</td>");c.push("</tr>")}c.push("</tbody>");c.push("</table>");return Elements.from(c.join(""))[0]}
function FastTable2(a,b){var c=new Element("table"),d=new Element("thead"),e=new Element("tr"),f=[];a.each(function(a){f.push(new Element("th",{html:a}))});e.adopt(f);d.adopt(e);a=new Element("tbody");var g=[];b.each(function(a){var b=new Element("tr"),c=[];a.each(function(a){c.push(new Element("td",{html:a}))});b.adopt(c);g.push(b)});a.adopt(g);return c.adopt(d,a)}var __start_time={},__prev_name;function __start__(a){__start_time[a]=new Date;__prev_name=a}
function __end__(a){"undefined"===typeof a&&(a=__prev_name);console.log(a+" took: "+(new Date-__start_time[a])/1E3+" seconds")}function getParameterByName(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec(location.search);return null==a?"":decodeURIComponent(a[1].replace(/\+/g," "))}
function AddConfirmNavigationNotification(a,b){(window.attachEvent||window.addEventListener)(window.attachEvent?"onbeforeunload":"beforeunload",function(c){if(b)return a})}
function EnableButtonShortcuts(a){"string"==typeOf(a)&&(a=$$(a));a.each(function(a){a.title.startsWith("Shortcut: ")&&!a.retrieve("shortcut")&&a.title.replace("Shortcut: ","").split(",").each(function(b){shortcut.add(b.trim(),function(){a.click()},{type:"keydown",propagate:!1,disable_in_input:!0,target:document,keycode:!1});a.store("shortcut",!0)})})}
function DisableButtonShortcuts(a){"string"==typeOf(a)&&(a=$$(a));a.each(function(a){a.title.startsWith("Shortcut: ")&&a.retrieve("shortcut")&&a.title.replace("Shortcut: ","").split(",").each(function(b){shortcut.remove(b.trim());a.eliminate("shortcut")})})}
Element.implement({EnableButtonShortcuts:function(){EnableButtonShortcuts(this.getElements("button"));return this},DisableButtonShortcuts:function(){DisableButtonShortcuts(this.getElements("button"));return this},Draggable:function(a){this.makeDraggable(a);return this}});function Evaluate(a,b){b=GridRow(b).getNext(":visible:enabled").rowIndex;a=a.replace(/\{Next Visible Row\}/g,b);return eval(a)}
function GetPropValue(a,b,c){if("object"===typeOf(a)){var d;if("BySampleType"in a){var e=(d=GridGetCell(c,"Type"))?"QC":"Sample";d=d in a.BySampleType?a.BySampleType[d]:e in a.BySampleType?a.BySampleType[e]:"Others"in a.BySampleType?a.BySampleType.Others:b;"object"===typeof d&&"eval"in d&&Evaluate(d.eval,c)}if("eval"in a)d=Evaluate(a.eval,c),console.log(d);else{for(var f in a)if(d=a[f],"When"in d&&ConditionMatches(d.When,c))return f;return b}return GetPropValue(d,b,c)}return a}
function Is(a,b,c,d,e){return b&&a in b&&!Conflicting(b[a],c,d,e)}
function Conflicting(a,b,c,d){b=b||null;c=c||_blk_test;switch(typeOf(a)){case "boolean":return!a;case "object":return"When"in a&&!ConditionMatches(a.When,d)||"MDL_Study"in a&&"NON_MDL_Study"in a&&Conflicting(a[_MDL_Study?"MDL_Study":"NON_MDL_Study"],b,c,d)||"NO_MS_MSD_DUP"in a&&"MS_MSD_DUP"in a&&Conflicting(a[_NO_MS_MSD_DUP?"NO_MS_MSD_DUP":"MS_MSD_DUP"],b,c,d)||"NO_MS_MSD_DUP_2"in a&&"MS_MSD_DUP_2"in a&&Conflicting(a[_NO_MS_MSD_DUP_2?"NO_MS_MSD_DUP_2":"MS_MSD_DUP_2"],b,c,d)||"Batch_Is_Open"in a&&
"Batch_Is_Closed"in a&&Conflicting(a[_batch_is_closed?"Batch_Is_Closed":"Batch_Is_Open"],b,c,d)||"ByMatrix"in a&&Conflicting(a.ByMatrix[_matrix in a.ByMatrix?_matrix:"Others"],b,c,d)||"ByGroup"in a&&Conflicting(a.ByGroup[_group in a.ByGroup?_group:"Others"],b,c,d)?!0:CheckConfliction(a,"OnlyForMatrix",_matrix)||CheckConfliction(a,"ExceptForMatrix",_matrix)||CheckConfliction(a,"OnlyForGroup",_group)||CheckConfliction(a,"ExceptForGroup",_group)||CheckConfliction(a,"OnlyForType",b)||CheckConfliction(a,
"ExceptForType",b)||CheckConfliction(a,"OnlyForTest",c)||CheckConfliction(a,"ExceptForTest",c);case "array":for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())if(!Conflicting(f.value,b,c,d))return!1;default:return a!=b}}function GetValueByName(a,b){return"BLK_TEST"==a?_blk_test:"undefined"!==typeof _GRID&&_GRID.columnExists(a)&&null!==b?GridGetText(b,a)||"":GetFieldValue(a)}
function ConditionMatches(a,b){if("object"===typeOf(a)){for(var c in a)if("$hidden"!=c){var d=a[c],e=GetValueByName(c,b);if("array"===typeOf(d)){var f=!1;d=$jscomp.makeIterator(d);for(var g=d.next();!g.done;g=d.next())AllConditionMatched(e,g.value)&&(f=!0);if(!f)return!1}else if("object"===typeOf(d)){if(!AllConditionMatched(e,d))return!1}else if(!e)return!1}return!0}if("array"===typeOf(a)){a=$jscomp.makeIterator(a);for(c=a.next();!c.done;c=a.next())if(ConditionMatches(c.value,b))return!0;return!1}}
function AllConditionMatched(a,b){if("object"==typeOf(b)){if("Is"in b){if(a!=b.Is)return!1}else if("IsNot"in b){if(a==b.IsNot)return!1}else if("IsGreaterThan"in b){if(a<=b.IsGreaterThan)return!1}else if("IsLessThan"in b){if(a>=b.IsLessThan)return!1}else if("In"in b){if(!b.In.includes(a))return!1}else if("NotIn"in b){if(b.NotIn.includes(a))return!1}else if("Contains"in b){if(!(a||"").contains(b.Contains))return!1}else if("NotContains"in b){if((a||"").contains(b.NotContains))return!1}else if("Match"in
b){if(!(a||"").match(b.Match))return!1}else if("NotMatch"in b&&(a||"").match(b.NotMatch))return!1;return!0}if("array"===typeOf(b)){b=$jscomp.makeIterator(b);for(var c=b.next();!c.done;c=b.next())if(AllConditionMatched(a,c.value))return!0;return!1}return b==a}
function CheckConfliction(a,b,c){if(b in a){var d=b.contains("ExceptFor");a=flatten(a[b]);if("string"==typeOf(a))return a==c?d:!d;if("array"==typeOf(a))return a.contains(c)?d:!d;if("object"==typeOf(a)&&"Contains"in a){a=a.Contains;if("string"==typeOf(a))return c.contains(a)?d:!d;if("array"==typeOf(a)){for(b=0;b<a.length;b++)if(c&&c.contains(a[b]))return d;return!d}if("object"==typeOf(a)){if("Or"in a){a=a.Or;for(b=0;b<a.length;b++)if(c&&c.contains(a[b]))return d;return!d}if("And"in a){a=a.And;for(b=
0;b<a.length;b++)if(!c||!c.contains(a[b]))return!d;return d}}}}return!1}
function GetLabelForDisplay(a,b){if(b&&"Label"in b)if(b=b.Label,"object"==typeof b)if("Dynamic"in b){var c=b.Dynamic;b=c.id;var d=c.key;c="format"in c?c.format:"";$(b)&&(a=$(b).get(d),c&&(a=c.replace("xxxx",a)))}else"ByMatrix"in b?(b=b.ByMatrix,_matrix in b?a=b[_matrix]:"Others"in b&&(a=b.Others)):"ByGroup"in b?(b=b.ByGroup,_group in b?a=b[_group]:"Others"in b&&(a=b.Others)):_group in b?a=b[_group]:"Others"in b&&(a=b.Others);else a=b;return a}
function TableFromData(a,b){b=Object.merge({table_id:"sample_table",table_class:"sample_table",column_id:null,column_status:"undefined"==typeof _TASK?null:_TASK.Done.Status+" On",row_class_by_status:{todo:"==null"},transpose:!1},b||{});var c=a.headers.indexOf(b.column_id),d=a.headers.indexOf(b.column_status),e='<table id="'+b.table_id+'" class="'+b.table_class+'">';b.transpose||(e+="<thead><tr>",a.headers.each(function(a,b){b!=c&&(e+="<th>"+a+"</th>")}),e+="</tr></thead>");e+="<tbody>";(b.transpose?
a.rows.transpose():a.rows).each(function(a){var f=[],k;for(k in b.row_class_by_status){var h=a[d];null!=h&&(h="'"+h+"'");var m=b.row_class_by_status[k],l=void 0;try{l=eval(h+m)}catch(n){l=!1}l&&f.push(k)}e+="<tr"+(f.length?' class="'+f.join(" ")+'"':"")+">";a.each(function(a,b){b!=c&&(e+="<td>"+(a||"")+"</td>")});e+="</tr>"});e+="</tbody>";return e+="</table>"}
function cssGetStyle(a,b){for(var c=0;c<document.styleSheets.length;c++)for(var d=document.styleSheets[c].rules||document.styleSheets[c].cssRules,e=0;e<d.length;e++)if(d[e].selectorText==a){if("undefined"==typeof b)return d[e].cssText?d[e].cssText:d[e].style.cssText;if(b in d[e].style&&d[e].style[b])return d[e].style[b]}return null}function cssAdd(a){var b=document.createElement("style");b.innerHTML=a;document.head.appendChild(b)}
function FitText(a){var b=parseInt(window.getComputedStyle(a,null).getPropertyValue("font-size"));if(a.getScrollWidth()>a.getWidth())for(;a.getScrollWidth()>a.getWidth()&&0<b;)b-=.1,a.setStyle("font-size",b+"px");else for(;a.getScrollWidth()<a.getWidth()&&100>b;)b+=.1,a.setStyle("font-size",b+"px")};
