/*
 MIT
*/
(function(v){"function"===typeof define&&define.amd?define(v):"undefined"!=typeof module&&"undefined"!=typeof module.exports?module.exports=v():window.Sortable=v()})(function(){function v(a,b){if(!a||!a.nodeType||1!==a.nodeType)throw"Sortable: `el` must be HTMLElement, and not "+{}.toString.call(a);this.el=a;this.options=b=ca({},b);a[H]=this;var c={group:null,sort:!0,disabled:!1,store:null,handle:null,scroll:!0,scrollSensitivity:30,scrollSpeed:10,draggable:/[uo]l/i.test(a.nodeName)?"li":">*",ghostClass:"sortable-ghost",
chosenClass:"sortable-chosen",dragClass:"sortable-drag",ignore:"a, img",filter:null,preventOnFilter:!0,animation:0,setData:function(a,b){a.setData("Text",b.textContent)},dropBubble:!1,dragoverBubble:!1,dataIdAttr:"data-id",delay:0,touchStartThreshold:S(window.devicePixelRatio,10)||1,forceFallback:!1,fallbackClass:"sortable-fallback",fallbackOnBody:!1,fallbackTolerance:0,fallbackOffset:{x:0,y:0},supportPointer:!1!==v.supportPointer},d;for(d in c)d in b||(b[d]=c[d]);da(b);for(var g in this)"_"===g.charAt(0)&&
"function"===typeof this[g]&&(this[g]=this[g].bind(this));this.nativeDraggable=b.forceFallback?!1:qa;m(a,"mousedown",this._onTapStart);m(a,"touchstart",this._onTapStart);b.supportPointer&&m(a,"pointerdown",this._onTapStart);this.nativeDraggable&&(m(a,"dragover",this),m(a,"dragenter",this));J.push(this._onDragOver);b.store&&this.sort(b.store.get(this))}function T(a,b){"clone"!==a.lastPullMode&&(b=!0);p&&p.state!==b&&(h(p,"display",b?"none":""),!b&&p.state&&(a.options.group.revertClone?(k.insertBefore(p,
I),a._animate(e,p)):k.insertBefore(p,e)),p.state=b)}function C(a,b,c){if(a){c=c||f;do if(">*"===b&&a.parentNode===c||ea(a,b))return a;while(a=ra(a))}return null}function ra(a){var b=a.host;return b&&b.nodeType?b:a.parentNode}function m(a,b,c){a.addEventListener(b,c,U)}function n(a,b,c){a.removeEventListener(b,c,U)}function A(a,b,c){if(a)if(a.classList)a.classList[c?"add":"remove"](b);else{var d=(" "+a.className+" ").replace(fa," ").replace(" "+b+" "," ");a.className=(d+(c?" "+b:"")).replace(fa," ")}}
function h(a,b,c){var d=a&&a.style;if(d){if(void 0===c)return f.defaultView&&f.defaultView.getComputedStyle?c=f.defaultView.getComputedStyle(a,""):a.currentStyle&&(c=a.currentStyle),void 0===b?c:c[b];b in d||(b="-webkit-"+b);d[b]=c+("string"===typeof c?"":"px")}}function ha(a,b,c){if(a){a=a.getElementsByTagName(b);b=0;var d=a.length;if(c)for(;b<d;b++)c(a[b],b);return a}return[]}function y(a,b,c,d,g,e,k,E,l){a=a||b[H];var q=f.createEvent("Event"),m=a.options,r="on"+c.charAt(0).toUpperCase()+c.substr(1);
q.initEvent(c,!0,!0);q.to=g||b;q.from=e||b;q.item=d||b;q.clone=p;q.oldIndex=k;q.newIndex=E;q.originalEvent=l;b.dispatchEvent(q);m[r]&&m[r].call(a,q)}function ia(a,b,c,d,g,e,k,E){var l=a[H],q=l.options.onMove,m;var r=f.createEvent("Event");r.initEvent("move",!0,!0);r.to=b;r.from=a;r.dragged=c;r.draggedRect=d;r.related=g||b;r.relatedRect=e||b.getBoundingClientRect();r.willInsertAfter=E;r.originalEvent=k;a.dispatchEvent(r);q&&(m=q.call(l,r,k));return m}function ja(a){a.draggable=!1}function sa(){V=!1}
function ta(a){a=a.tagName+a.className+a.src+a.href+a.textContent;for(var b=a.length,c=0;b--;)c+=a.charCodeAt(b);return c.toString(36)}function M(a,b){var c=0;if(!a||!a.parentNode)return-1;for(;a&&(a=a.previousElementSibling);)"TEMPLATE"===a.nodeName.toUpperCase()||">*"!==b&&!ea(a,b)||c++;return c}function ea(a,b){if(a)try{if(a.matches)return a.matches(b);if(a.msMatchesSelector)return a.msMatchesSelector(b)}catch(c){}return!1}function ka(a,b){var c,d;return function(){void 0===c&&(c=arguments,d=this,
K(function(){1===c.length?a.call(d,c[0]):a.apply(d,c);c=void 0},b))}}function ca(a,b){if(a&&b)for(var c in b)b.hasOwnProperty(c)&&(a[c]=b[c]);return a}function la(a){return W&&W.dom?W.dom(a).cloneNode(!0):ma?ma(a).clone(!0)[0]:a.cloneNode(!0)}function ua(a){N.length=0;a=a.getElementsByTagName("input");for(var b=a.length;b--;){var c=a[b];c.checked&&N.push(c)}}function O(a){return K(a,0)}if("undefined"===typeof window||!window.document)return function(){throw Error("Sortable.js requires a window with a document");
};var e,x,l,p,k,I,X,z,Y,Z,aa,P,ba,w,t,L,Q,D={},F,u,R,fa=/\s+/g,va=/left|right|inline/,H="Sortable"+(new Date).getTime(),B=window,f=B.document,S=B.parseInt,K=B.setTimeout,ma=B.jQuery||B.Zepto,W=B.Polymer,U=!1,na=!1,qa="draggable"in f.createElement("div"),oa=function(a){if(navigator.userAgent.match(/(?:Trident.*rv[ :]?11\.|msie)/i))return!1;a=f.createElement("x");a.style.cssText="pointer-events:auto";return"auto"===a.style.pointerEvents}(),V=!1,G=Math.abs,pa=Math.min,N=[],J=[],wa=function(){return!1},
xa=ka(function(a,b,c){if(c&&b.scroll){var d=c[H],g=b.scrollSensitivity,e=b.scrollSpeed,k=a.clientX,E=a.clientY,l=window.innerWidth,m=window.innerHeight,h,r;if(Y!==c&&(z=b.scroll,Y=c,Z=b.scrollFn,!0===z)){z=c;do if(z.offsetWidth<z.scrollWidth||z.offsetHeight<z.scrollHeight)break;while(z=z.parentNode)}if(z){var f=z;b=z.getBoundingClientRect();var n=(G(b.right-k)<=g)-(G(b.left-k)<=g);var p=(G(b.bottom-E)<=g)-(G(b.top-E)<=g)}n||p||(n=(l-k<=g)-(k<=g),p=(m-E<=g)-(E<=g),(n||p)&&(f=B));if(D.vx!==n||D.vy!==
p||D.el!==f)D.el=f,D.vx=n,D.vy=p,clearInterval(D.pid),f&&(D.pid=setInterval(function(){r=p?p*e:0;h=n?n*e:0;if("function"!==typeof Z||"continue"===Z.call(d,h,r,a,u,f))f===B?B.scrollTo(B.pageXOffset+h,B.pageYOffset+r):(f.scrollTop+=r,f.scrollLeft+=h)},24))}},30),da=function(a){function b(a,b){if(null==a||!0===a)if(a=c.name,null==a)return wa;return"function"===typeof a?a:function(c,d){c=d.options.group.name;return b?a:a&&(a.join?-1<a.indexOf(c):c==a)}}var c={},d=a.group;d&&"object"==typeof d||(d={name:d});
c.name=d.name;c.checkPull=b(d.pull,!0);c.checkPut=b(d.put);c.revertClone=d.revertClone;a.group=c};try{window.addEventListener("test",null,Object.defineProperty({},"passive",{get:function(){na=!1;U={capture:!1,passive:na}}}))}catch(a){}v.prototype={constructor:v,_onTapStart:function(a){var b=this,c=this.el,d=this.options,g=d.preventOnFilter,k=a.type,l=a.touches&&a.touches[0],f=(l||a).target,m=a.target.shadowRoot&&a.path&&a.path[0]||f,h=d.filter;ua(c);if(!(e||/mousedown|pointerdown/.test(k)&&0!==a.button||
d.disabled||m.isContentEditable)&&(f=C(f,d.draggable,c))&&X!==f){var n=M(f,d.draggable);if("function"===typeof h){if(h.call(this,a,f,this)){y(b,m,"filter",f,c,c,n);g&&a.preventDefault();return}}else if(h&&(h=h.split(",").some(function(a){if(a=C(m,a.trim(),c))return y(b,a,"filter",f,c,c,n),!0}))){g&&a.preventDefault();return}d.handle&&!C(m,d.handle,c)||this._prepareDragStart(a,l,f,n)}},_prepareDragStart:function(a,b,c,d){var g=this,f=g.el,l=g.options,h=f.ownerDocument;c&&!e&&c.parentNode===f&&(F=a,
k=f,e=c,x=e.parentNode,I=e.nextSibling,X=c,L=l.group,w=d,this._lastX=(b||a).clientX,this._lastY=(b||a).clientY,e.style["will-change"]="all",c=function(){g._disableDelayedDrag();e.draggable=g.nativeDraggable;A(e,l.chosenClass,!0);g._triggerDragStart(a,b);y(g,k,"choose",e,k,k,w)},l.ignore.split(",").forEach(function(a){ha(e,a.trim(),ja)}),m(h,"mouseup",g._onDrop),m(h,"touchend",g._onDrop),m(h,"touchcancel",g._onDrop),m(h,"selectstart",g),l.supportPointer&&m(h,"pointercancel",g._onDrop),l.delay?(m(h,
"mouseup",g._disableDelayedDrag),m(h,"touchend",g._disableDelayedDrag),m(h,"touchcancel",g._disableDelayedDrag),m(h,"mousemove",g._disableDelayedDrag),m(h,"touchmove",g._delayedDragTouchMoveHandler),l.supportPointer&&m(h,"pointermove",g._delayedDragTouchMoveHandler),g._dragStartTimer=K(c,l.delay)):c())},_delayedDragTouchMoveHandler:function(a){pa(G(a.clientX-this._lastX),G(a.clientY-this._lastY))>=this.options.touchStartThreshold&&this._disableDelayedDrag()},_disableDelayedDrag:function(){var a=this.el.ownerDocument;
clearTimeout(this._dragStartTimer);n(a,"mouseup",this._disableDelayedDrag);n(a,"touchend",this._disableDelayedDrag);n(a,"touchcancel",this._disableDelayedDrag);n(a,"mousemove",this._disableDelayedDrag);n(a,"touchmove",this._disableDelayedDrag);n(a,"pointermove",this._disableDelayedDrag)},_triggerDragStart:function(a,b){(b=b||("touch"==a.pointerType?a:null))?(F={target:e,clientX:b.clientX,clientY:b.clientY},this._onDragStart(F,"touch")):this.nativeDraggable?(m(e,"dragend",this),m(k,"dragstart",this._onDragStart)):
this._onDragStart(F,!0);try{f.selection?O(function(){f.selection.empty()}):window.getSelection().removeAllRanges()}catch(c){}},_dragStarted:function(){if(k&&e){var a=this.options;A(e,a.ghostClass,!0);A(e,a.dragClass,!1);v.active=this;y(this,k,"start",e,k,k,w)}else this._nulling()},_emulateDragOver:function(){if(u&&(this._lastX!==u.clientX||this._lastY!==u.clientY)){this._lastX=u.clientX;this._lastY=u.clientY;oa||h(l,"display","none");for(var a=f.elementFromPoint(u.clientX,u.clientY),b=a,c=J.length;a&&
a.shadowRoot;)b=a=a.shadowRoot.elementFromPoint(u.clientX,u.clientY);if(b){do{if(b[H]){for(;c--;)J[c]({clientX:u.clientX,clientY:u.clientY,target:a,rootEl:b});break}a=b}while(b=b.parentNode)}oa||h(l,"display","")}},_onTouchMove:function(a){if(F){var b=this.options,c=b.fallbackTolerance,d=b.fallbackOffset;b=a.touches?a.touches[0]:a;var e=b.clientX-F.clientX+d.x;d=b.clientY-F.clientY+d.y;e=a.touches?"translate3d("+e+"px,"+d+"px,0)":"translate("+e+"px,"+d+"px)";if(!v.active){if(c&&pa(G(b.clientX-this._lastX),
G(b.clientY-this._lastY))<c)return;this._dragStarted()}this._appendGhost();R=!0;u=b;h(l,"webkitTransform",e);h(l,"mozTransform",e);h(l,"msTransform",e);h(l,"transform",e);a.preventDefault()}},_appendGhost:function(){if(!l){var a=e.getBoundingClientRect(),b=h(e),c=this.options;l=e.cloneNode(!0);A(l,c.ghostClass,!1);A(l,c.fallbackClass,!0);A(l,c.dragClass,!0);h(l,"top",a.top-S(b.marginTop,10));h(l,"left",a.left-S(b.marginLeft,10));h(l,"width",a.width);h(l,"height",a.height);h(l,"opacity","0.8");h(l,
"position","fixed");h(l,"zIndex","100000");h(l,"pointerEvents","none");c.fallbackOnBody&&f.body.appendChild(l)||k.appendChild(l);b=l.getBoundingClientRect();h(l,"width",2*a.width-b.width);h(l,"height",2*a.height-b.height)}},_onDragStart:function(a,b){var c=this,d=a.dataTransfer,g=c.options;c._offUpEvents();L.checkPull(c,c,e,a)&&(p=la(e),p.draggable=!1,p.style["will-change"]="",h(p,"display","none"),A(p,c.options.chosenClass,!1),c._cloneId=O(function(){k.insertBefore(p,e);y(c,k,"clone",e)}));A(e,g.dragClass,
!0);b?("touch"===b?(m(f,"touchmove",c._onTouchMove),m(f,"touchend",c._onDrop),m(f,"touchcancel",c._onDrop),g.supportPointer&&(m(f,"pointermove",c._onTouchMove),m(f,"pointerup",c._onDrop))):(m(f,"mousemove",c._onTouchMove),m(f,"mouseup",c._onDrop)),c._loopId=setInterval(c._emulateDragOver,50)):(d&&(d.effectAllowed="move",g.setData&&g.setData.call(c,d,e)),m(f,"drop",c),c._dragStartId=O(c._dragStarted))},_onDragOver:function(a){var b=this.el,c;var d=this.options;var g=d.group;var f=v.active,m=L===g,
n=!1,t=d.sort;void 0!==a.preventDefault&&(a.preventDefault(),!d.dragoverBubble&&a.stopPropagation());if(!e.animated&&(R=!0,f&&!d.disabled&&(m?t||(c=!k.contains(e)):Q===this||(f.lastPullMode=L.checkPull(this,f,e,a))&&g.checkPut(this,f,e,a))&&(void 0===a.rootEl||a.rootEl===this.el)&&(xa(a,d,this.el),!V)))if(d=C(a.target,d.draggable,b),g=e.getBoundingClientRect(),Q!==this&&(Q=this,n=!0),c)T(f,!0),x=k,p||I?k.insertBefore(e,p||I):t||k.appendChild(e);else if(!(c=0===b.children.length||b.children[0]===l)&&
(c=b===a.target)&&(c=b.lastElementChild.getBoundingClientRect(),c=5<a.clientY-(c.top+c.height)||5<a.clientX-(c.left+c.width)),c){0!==b.children.length&&b.children[0]!==l&&b===a.target&&(d=b.lastElementChild);if(d){if(d.animated)return;var q=d.getBoundingClientRect()}T(f,m);!1!==ia(k,b,e,g,d,q,a)&&(e.contains(b)||(b.appendChild(e),x=b),this._animate(g,e),d&&this._animate(q,d))}else if(d&&!d.animated&&d!==e&&void 0!==d.parentNode[H]){aa!==d&&(aa=d,P=h(d),ba=h(d.parentNode));q=d.getBoundingClientRect();
var u=q.right-q.left;c=q.bottom-q.top;var r=va.test(P.cssFloat+P.display)||"flex"==ba.display&&0===ba["flex-direction"].indexOf("row");t=d.offsetWidth>e.offsetWidth;var y=d.offsetHeight>e.offsetHeight,z=.5<(r?(a.clientX-q.left)/u:(a.clientY-q.top)/c);u=d.nextElementSibling;var w=!1;r?(n=e.offsetTop,r=d.offsetTop,w=n===r?d.previousElementSibling===e&&!t||z&&t:d.previousElementSibling===e||e.previousElementSibling===d?.5<(a.clientY-q.top)/c:r>n):n||(w=u!==e&&!y||z&&y);a=ia(k,b,e,g,d,q,a,w);if(!1!==
a){if(1===a||-1===a)w=1===a;V=!0;K(sa,30);T(f,m);e.contains(b)||(w&&!u?b.appendChild(e):d.parentNode.insertBefore(e,w?u:d));x=e.parentNode;this._animate(g,e);this._animate(q,d)}}},_animate:function(a,b){var c=this.options.animation;if(c){var d=b.getBoundingClientRect();1===a.nodeType&&(a=a.getBoundingClientRect());h(b,"transition","none");h(b,"transform","translate3d("+(a.left-d.left)+"px,"+(a.top-d.top)+"px,0)");h(b,"transition","all "+c+"ms");h(b,"transform","translate3d(0,0,0)");clearTimeout(b.animated);
b.animated=K(function(){h(b,"transition","");h(b,"transform","");b.animated=!1},c)}},_offUpEvents:function(){var a=this.el.ownerDocument;n(f,"touchmove",this._onTouchMove);n(f,"pointermove",this._onTouchMove);n(a,"mouseup",this._onDrop);n(a,"touchend",this._onDrop);n(a,"pointerup",this._onDrop);n(a,"touchcancel",this._onDrop);n(a,"pointercancel",this._onDrop);n(a,"selectstart",this)},_onDrop:function(a){var b=this.el,c=this.options;clearInterval(this._loopId);clearInterval(D.pid);clearTimeout(this._dragStartTimer);
clearTimeout(this._cloneId);clearTimeout(this._dragStartId);n(f,"mouseover",this);n(f,"mousemove",this._onTouchMove);this.nativeDraggable&&(n(f,"drop",this),n(b,"dragstart",this._onDragStart));this._offUpEvents();if(a&&(R&&(a.preventDefault(),!c.dropBubble&&a.stopPropagation()),l&&l.parentNode&&l.parentNode.removeChild(l),(k===x||"clone"!==v.active.lastPullMode)&&p&&p.parentNode&&p.parentNode.removeChild(p),e&&(this.nativeDraggable&&n(e,"dragend",this),ja(e),e.style["will-change"]="",A(e,this.options.ghostClass,
!1),A(e,this.options.chosenClass,!1),y(this,k,"unchoose",e,x,k,w,null,a),k!==x?(t=M(e,c.draggable),0<=t&&(y(null,x,"add",e,x,k,w,t,a),y(this,k,"remove",e,x,k,w,t,a),y(null,x,"sort",e,x,k,w,t,a),y(this,k,"sort",e,x,k,w,t,a))):e.nextSibling!==I&&(t=M(e,c.draggable),0<=t&&(y(this,k,"update",e,x,k,w,t,a),y(this,k,"sort",e,x,k,w,t,a))),v.active))){if(null==t||-1===t)t=w;y(this,k,"end",e,x,k,w,t,a);this.save()}this._nulling()},_nulling:function(){k=e=x=l=I=p=X=z=Y=F=u=R=t=aa=P=Q=L=v.active=null;N.forEach(function(a){a.checked=
!0});N.length=0},handleEvent:function(a){switch(a.type){case "drop":case "dragend":this._onDrop(a);break;case "dragover":case "dragenter":e&&(this._onDragOver(a),a.dataTransfer&&(a.dataTransfer.dropEffect="move"),a.preventDefault());break;case "mouseover":this._onDrop(a);break;case "selectstart":a.preventDefault()}},toArray:function(){for(var a=[],b,c=this.el.children,d=0,e=c.length,f=this.options;d<e;d++)b=c[d],C(b,f.draggable,this.el)&&a.push(b.getAttribute(f.dataIdAttr)||ta(b));return a},sort:function(a){var b=
{},c=this.el;this.toArray().forEach(function(a,e){e=c.children[e];C(e,this.options.draggable,c)&&(b[a]=e)},this);a.forEach(function(a){b[a]&&(c.removeChild(b[a]),c.appendChild(b[a]))})},save:function(){var a=this.options.store;a&&a.set(this)},closest:function(a,b){return C(a,b||this.options.draggable,this.el)},option:function(a,b){var c=this.options;if(void 0===b)return c[a];c[a]=b;"group"===a&&da(c)},destroy:function(){var a=this.el;a[H]=null;n(a,"mousedown",this._onTapStart);n(a,"touchstart",this._onTapStart);
n(a,"pointerdown",this._onTapStart);this.nativeDraggable&&(n(a,"dragover",this),n(a,"dragenter",this));Array.prototype.forEach.call(a.querySelectorAll("[draggable]"),function(a){a.removeAttribute("draggable")});J.splice(J.indexOf(this._onDragOver),1);this._onDrop();this.el=a=null}};m(f,"touchmove",function(a){v.active&&a.preventDefault()});v.utils={on:m,off:n,css:h,find:ha,is:function(a,b){return!!C(a,b,a)},extend:ca,throttle:ka,closest:C,toggleClass:A,clone:la,index:M,nextTick:O,cancelNextTick:function(a){return clearTimeout(a)}};
v.create=function(a,b){return new v(a,b)};v.version="1.7.0";return v});
