String.prototype.toProperCase||(String.prototype.toProperCase=function(){return this.replace(/\w\S*/g,(a)=>a.charAt(0).toUpperCase()+a.substr(1).toLowerCase())});
String.prototype.toTitleCase||(String.prototype.toTitleCase=function(){var a,b,c,d;c=this.replace(/([^\W_]+[^\s-]*) */g,(a)=>a.charAt(0).toUpperCase()+a.substr(1).toLowerCase());d="A An The And But Or For Nor As At By For From In Into Near Of On Onto To With".split(" ");a=0;for(b=d.length;a<b;a++)c=c.replace(new RegExp("\\s"+d[a]+"\\s","g"),(a)=>a.toLowerCase());d=["Id","Tv"];a=0;for(b=d.length;a<b;a++)c=c.replace(new RegExp("\\b"+d[a]+"\\b","g"),d[a].toUpperCase());return c});
String.prototype.between||(String.prototype.between=function(a,b){return-1===this.indexOf(a)||-1===this.indexOf(b)?null:this.substring(this.indexOf(a)+a.length,this.lastIndexOf(b))});String.prototype.urlEncode||(String.prototype.urlEncode=function(){return encodeURI(this).replace(/#/g,"%23").replace(/\+/g,"%2b").replace(/&/g,"%26")});
String.prototype.htmlDecode||(String.prototype.htmlDecode=function(){return this.replace(/&amp;/gi,"&").replace(/&lt;/gi,"<").replace(/&gt;/gi,">").replace(/&quot;/gi,'"')});String.prototype.htmlEncode||(String.prototype.htmlEncode=function(){return this.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;")});String.prototype.contains||(String.prototype.contains=function(a){return 0<=this.indexOf(a)});
Number.prototype.in||(Number.prototype.in=function(){if(1==arguments.length){var a=arguments[0];return Array.isArray(a)?0<=a.indexOf(this):"object"===typeof a?this in a:a===this}return 0<=Array.from(arguments).indexOf(+this)});String.prototype.in||(String.prototype.in=function(){if(1==arguments.length){var a=arguments[0];return Array.isArray(a)?0<=a.indexOf(""+this):"object"===typeof a?this in a:a==this}return 0<=Array.from(arguments).indexOf(""+this)});
String.prototype.startsWith||(String.prototype.startsWith=function(a){return 0===this.indexOf(a)});String.prototype.endsWith||(String.prototype.endsWith=function(a){return-1!==this.indexOf(a,this.length-a.length)});String.prototype.left||(String.prototype.left=function(a){return 0>=a?"":a>this.length?this:this.substring(0,a)});String.prototype.right||(String.prototype.right=function(a){if(0>=a)return"";if(a>this.length)return this;var b=this.length;return this.substring(b,b-a)});
String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^\s+/,"").replace(/\s+$/,"")});String.prototype.padLeft||(String.prototype.padLeft=function(a,b){b=b||"0";for(t="";this.length+t.length<a;)t+=b;return t+this});String.prototype.padRight||(String.prototype.padRight=function(a,b){b=b||"0";for(t="";this.length+t.length<a;)t+=b;return this+t});
String.prototype.addCommas||(String.prototype.addCommas=function(){for(var a=this.split("."),b=a[0],a=1<a.length?"."+a[1]:"",c=/(\d+)(\d{3})/;c.test(b);)b=b.replace(c,"$1,$2");return b+a});String.prototype.isNumber||(String.prototype.isNumber=function(){return!isNaN(parseFloat(this))&&isFinite(this)});String.prototype.repeat||(String.prototype.repeat=function(a){return Array((a||0)+1).join(this)});Number.prototype.toCurrency||(Number.prototype.toCurrency=function(){return this.toFixed(2).addCommas()});
String.prototype.toNumber||(String.prototype.toNumber=function(){return+this.replace(",","")});Number.prototype.round||(Number.prototype.round=function(a){"undefined"===typeof a&&(a=0);return 10*Math.round(10*this^a)^a});function isNumber(a){return!isNaN(parseFloat(a))&&isFinite(a)}function escapeRegExp(a){return a.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&")}
String.prototype.escapeRegExp||(String.prototype.escapeRegExp=function(){return this.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g,"\\$&")});function html2text(a){return a.replace(/<[^>]*>?/g,"")}String.prototype.html2text||(String.prototype.html2text=function(){return this.replace(/<[^>]*>?/g,"")});String.prototype.replaceAll=function(a,b){return this.replace(new RegExp(a,"g"),b)};String.prototype.toClassName=function(){return this.replace(/[\/\ \(\)\#]/g,"_")};
