var SexyAlertBox=new Class({Implements:[Chain,Options],options:{name:"SexyAlertBox",zIndex:65555,returnValue:!1,onComplete(){},BoxStyles:{width:500},OverlayStyles:{"background-color":"#000",opacity:.7},showDuration:200,showEffect:Fx.Transitions.linear,closeDuration:100,closeEffect:Fx.Transitions.linear,moveDuration:500,moveEffect:Fx.Transitions.Back.easeOut,onShowStart(){if(this.options.onShowStart)this.options.onShowStart()},onShowComplete(){if(this.options.onShowComplete)this.options.onShowComplete()},
onCloseStart(){if(this.options.onCloseStart)this.options.onCloseStart()},onCloseComplete(){if(this.options.onCloseComplete)this.options.onCloseComplete();this.options.onComplete(this.options.returnValue)}},initialize(b){this.i=0;this.setOptions(this.options,b);this.Overlay=new Element("div",{id:"BoxOverlay",styles:{display:"none","background-color":this.options.OverlayStyles["background-color"],opacity:0,"z-index":this.options.zIndex,top:"0",left:"0",position:"fixed",width:"100%",height:"100%"}});
this.Content=new Element("div",{id:this.options.name+"-BoxContenedor"});this.Contenedor=(new Element("div",{id:this.options.name+"-BoxContent"})).adopt(this.Content);this.InBox=(new Element("div",{id:this.options.name+"-InBox"})).adopt(this.Contenedor);this.Box=(new Element("div",{id:this.options.name+"-Box",styles:{display:"none","z-index":this.options.zIndex+2,position:"absolute",top:"0",left:"0",width:this.options.BoxStyles.width+"px"}})).adopt(this.InBox);this.Overlay.inject(document.body);this.Box.inject(document.body);
window.addEvent("resize",function(){1==this.options.display&&this.replaceBox()}.bind(this));window.addEvent("scroll",this.replaceBox.bind(this));window.addEvent("keydown",(a)=>{switch(a.key){case "enter":if("TEXTAREA"==a.target.tagName&&!a.control)break;a=$$("div[id$=-Buttons] input[type=submit][id$=Ok]");0<a.length&&a[0].click();break;case "esc":a=$$("div[id$=-Buttons] input[type=submit][id$=Cancel]"),0<a.length&&a[0].click()}})},display(b){this.Transition&&this.Transition.cancel();0==this.options.display&&
0!=b||1==b?(Browser.ie&&$$("select","object","embed").each((a)=>{a.style.visibility="hidden"}),this.Overlay.setStyle("display","block"),this.options.display=1,this.fireEvent("onShowStart",[this.Overlay]),this.Transition=(new Fx.Tween(this.Overlay,{property:"opacity",duration:this.options.showDuration,transition:this.options.showEffect,onComplete:function(){var a=window.getSize(),b=window.getScroll();this.Box.setStyles({display:"block",left:(b.x+(a.x-this.options.BoxStyles.width)/2).toInt()});this.replaceBox();
this.fireEvent("onShowComplete",[this.Overlay]);this.PromptInput&&this.PromptInput.select()}.bind(this)})).start(this.options.OverlayStyles.opacity)):(Browser.ie&&$$("select","object","embed").each((a)=>{a.style.visibility="visible"}),this.queue.delay(500,this),this.Box.setStyles({display:"none",top:0}),this.Content.empty(),this.options.display=0,this.fireEvent("onCloseStart",[this.Overlay]),this.Transition=(new Fx.Tween(this.Overlay,{property:"opacity",duration:this.options.closeDuration,transition:this.options.closeEffect,
onComplete:function(){this.Overlay.setStyle("display","none");this.fireEvent("onCloseComplete",[this.Overlay])}.bind(this)})).start(0))},replaceBox(){if(1==this.options.display){var b=window.getSize(),a=window.getScroll();this.MoveBox&&this.MoveBox.cancel();this.MoveBox=(new Fx.Morph(this.Box,{duration:this.options.moveDuration,transition:this.options.moveEffect})).start({left:(a.x+(b.x-this.options.BoxStyles.width)/2).toInt(),top:(a.y+(b.y-this.Box.offsetHeight)/2).toInt()})}},queue(){this.i--;this.callChain()},
messageBox(b,a,c,d){this.chain(function(){c=Object.append({textBoxBtnOk:"OK",textBoxBtnCancel:"Cancel",iconClass:"",textBoxInputPrompt:null,password:!1,onShowComplete(){},onComplete(){}},c||{});this.options.onShowComplete=c.onShowComplete;this.options.onComplete=c.onComplete;this.ContenedorBotones=new Element("div",{id:this.options.name+"-Buttons"});if("alert"==b||"info"==b||"error"==b){this.AlertBtnOk=new Element("input",{id:"BoxAlertBtnOk",type:"submit",value:c.textBoxBtnOk});this.AlertBtnOk.addEvent("click",
function(a){a.stop();this.options.returnValue=!0;this.display(0)}.bind(this));var e={alert:"BoxAlert",error:"BoxError",info:"BoxInfo"};this.Content.setProperty("class",c.iconClass||e[b]).set("html",a);this.AlertBtnOk.inject(this.ContenedorBotones);this.ContenedorBotones.inject(this.Content);this.display(1)}else"confirm"==b?(this.ConfirmBtnOk=new Element("input",{id:"BoxConfirmBtnOk",type:"submit",value:c.textBoxBtnOk}),this.ConfirmBtnCancel=new Element("input",{id:"BoxConfirmBtnCancel",type:"submit",
value:c.textBoxBtnCancel}),this.ConfirmBtnOk.addEvent("click",function(a){a.stop();this.options.returnValue=!0;this.display(0)}.bind(this)),this.ConfirmBtnCancel.addEvent("click",function(a){a.stop();this.options.returnValue=!1;this.display(0)}.bind(this)),this.Content.setProperty("class",c.iconClass||"BoxConfirm").set("html",a),this.ConfirmBtnOk.inject(this.ContenedorBotones),this.ConfirmBtnCancel.inject(this.ContenedorBotones),this.ContenedorBotones.inject(this.Content),this.display(1)):"prompt"==
b?(this.PromptBtnOk=new Element("input",{id:"BoxPromptBtnOk",type:"submit",value:c.textBoxBtnOk}),this.PromptBtnCancel=new Element("input",{id:"BoxPromptBtnCancel",type:"submit",value:c.textBoxBtnCancel}),c.multiplelines?this.PromptInput=new Element("textarea",{id:"BoxPromptInput",html:d}):(b=c.password?"password":"text",this.PromptInput=new Element("input",{id:"BoxPromptInput",type:b,value:d})),this.PromptBtnOk.addEvent("click",function(a){a.stop();this.options.returnValue=this.PromptInput.value;
this.display(0)}.bind(this)),this.PromptBtnCancel.addEvent("click",function(a){a.stop();this.options.returnValue=!1;this.display(0)}.bind(this)),this.Content.setProperty("class",c.iconClass||"BoxPrompt").set("html",a+"<br />"),this.PromptInput.inject(this.Content),(new Element("br")).inject(this.Content),this.PromptBtnOk.inject(this.ContenedorBotones),this.PromptBtnCancel.inject(this.ContenedorBotones),this.ContenedorBotones.inject(this.Content),this.display(1)):"custom"==b?(this.Content.setProperty("class",
c.iconClass||"BoxCustom").set("html",a),c.textBoxBtnOk&&(this.PromptBtnOk=(new Element("input",{id:"BoxPromptBtnOk",type:"submit",value:c.textBoxBtnOk,events:{click:function(a){a.stop();a={};for(var b in d){var c=$$(".BoxCustom #"+b);1==c.length?a[b]=c[0][d[b]]:(c=$$(".BoxCustom #"+b+":checked"),a[b]=c.length?c[0][d[b]]:null)}this.options.returnValue=a;this.display(0)}.bind(this)}})).inject(this.ContenedorBotones)),c.textBoxBtnCancel&&(this.PromptBtnCancel=(new Element("input",{id:"BoxPromptBtnCancel",
type:"submit",value:c.textBoxBtnCancel,events:{click:function(a){a.stop();this.options.returnValue=!1;this.display(0)}.bind(this)}})).inject(this.ContenedorBotones)),this.ContenedorBotones.inject(this.Content),this.display(1)):(this.options.returnValue=!1,this.display(0))});this.i++;1==this.i&&this.callChain()},alert(b,a){this.messageBox("alert",b,a)},info(b,a){this.messageBox("info",b,a)},error(b,a){this.messageBox("error",b,a)},confirm(b,a){this.messageBox("confirm",b,a)},prompt(b,a,c){this.messageBox("prompt",
b,c,a)},custom(b,a,c){this.messageBox("custom",b,c,a)}});SexyAlertBox.implement(new Events,new Options);"undefined"!=typeof exports&&(exports.SexyAlertBox=SexyAlertBox);
