StyleWriter={createStyle:function(a,b){try{if(!document.id(b)||!b){var c=(new Element("style",{id:b||"",type:"text/css"})).inject($$("head")[0]);Browser.ie?c.styleSheet.cssText=a:c.set("text",a)}}catch(d){}},removeStyle:function(a){$$("style#"+a).dispose()}};Array.implement({setValue:function(a,b,c,d,e){return this.each(function(f){return f.setValue(a,b,c,d,e)})},select:function(){return this.each(function(a){return a.select()})}});
Elements.implement({setValue:function(a,b,c,d,e){return this.each(function(f){return f.setValue(a,b,c,d,e)})},select:function(){return this.each(function(a){return a.select()})}});
Element.implement({setValue:function(a,b,c,d,e){if(["td","th"].contains(this.get("tag"))){if(!this.getParent(".ariaGrid").retrieve("ariaGrid_object").setTD(this,a,b,c,d,e))throw"Error set cell value";return this}},setFocus:function(){if(["td","th"].contains(this.get("tag")))return this.getParent(".ariaGrid").retrieve("ariaGrid_object").setFocus(this),this},select:function(){if(["td","th"].contains(this.get("tag")))return this.getParent(".ariaGrid").retrieve("ariaGrid_object").setSelection(this),this},
getColumnHeader:function(){if(["td","th"].contains(this.get("tag")))return this.getParent(".ariaGrid").retrieve("ariaGrid_object").getColumnHeader(this)},getRowHeader:function(){if(["td","th"].contains(this.get("tag")))return this.getParent(".ariaGrid").retrieve("ariaGrid_object").getRowHeader(this)},startEdit:function(){if(["td","th"].contains(this.get("tag")))return this.getParent(".ariaGrid").retrieve("ariaGrid_object").startEdit(this)}});Element.Properties.AccessibleGrid={get:function(){return this.retrieve("ariaGrid_object")}};
AccessibleGrid=Class.refactor(HtmlTable,{initialize:function(){var a=this;this.previous.apply(this,arguments);this.element.setProperties({role:"grid","aria-describedby":"gridTitle"});this.element.addClass("ariaGrid");this.element.store("ariaGrid_object",this);this.thead=this.element.getElement("thead");this.tbody=this.element.getElement("tbody");this.currentActive=this.thead.getElement("th");this.selection=[];this.multiSelectActive=this.multiSelect=!1;this.buffer=[];this.shift=!1;this.editingCell=
null;this.initEvents();this.sortable||this.disableHeader();document.html.addEvent("click",function(b){a.editingCell&&b.target.getParent("td")!=a.editingCell&&a.finishEdit()});document.addEventListener("copy",function(b){if("TD"!==b.target.tagName)return!1;var c=getSelectionHtml();c?b.clipboardData.setData("text/plain",c):(a.buffer.length=0,a.selection.each(function(b){return a.buffer.push(b.get("data"))}),b.clipboardData.setData("text/plain",a.buffer.join("\n")),b.preventDefault())});document.addEventListener("paste",
function(b){if("TD"!==b.target.tagName)return!1;b=b.clipboardData.getData("Text").trimRight();a.buffer=b.split(/\r?\n/);if(1==a.selection.length){b=a.selection[0];for(var c=0;c<a.buffer.length;c++){var d=b.get("data"),e=a.buffer[c%a.buffer.length];e!=d&&b.setValue(e,!1,!1,!1,!0);if(d=b.getParent().getNext(":visible:enabled"))b=d.getElement("td:nth-child("+(b.cellIndex+1)+")");else break}}else a.selection.each(function(b,c){var d=b.get("data");c=a.buffer[c%a.buffer.length];c!=d&&b.setValue(c,!1,!1,
!1,!0)})})},rowCount:function(){return this.tbody.getElements("tr").length},columnCount:function(){return this.thead.getElements("th").length},sort:function(){this.previous.apply(this,arguments);document.activeElement.setProperty("aria-sort",this.sorted.reverse?"descending":"ascending").getSiblings().setProperty("aria-sort","none")},push:function(a,b,c,d,e){var f=this;b?Object.append(b,{role:"row"}):b={role:"row"};if("element"==typeOf(a)&&"tr"==a.get("tag"))return a.setProperty("role","row"),a.inject(c||
this.body,e),{tr:a,tds:a.getChildren("td")};a=a.map(function(a,b){d=d||"td";var c=new Element(d,a?a.properties:{});a=(a?a.content:"")||a;var e=typeOf(a);c.setProperties({role:"th"==d?"columnheader":"gridcell",tabindex:"-1"});["element","array","collection","elements"].contains(e)?c.adopt(a):(e=null,c.set("data",a),"function"==typeOf(f.options.formatter)&&(b=f.options.formatter(b,a,c),"object"==typeOf(b)?(a=b.text,"title"in b&&(e=b.title)):a=b),c.set("html",a),e&&c.set("title",e));return c});return{tr:(new Element("tr",
b)).inject(c||this.body,e).adopt(a),tds:a}},initEvents:function(){var a=this;this.currentActive.setProperty("tabindex","0");this.thead.getElements("th").addEvents({focus:function(b){b.target.hasClass("disabled")?a.currentActive.setFocus():(a.currentActive.setProperty("tabindex","-1"),a.currentActive=b.target,b.target.setProperty("tabindex","0"))},click:function(b){a.editingCell&&a.finishEdit();b.target.setFocus()},keydown:function(b){"right left down home end enter".split(" ").contains(b.key)&&(b.stop(),
a[b.key](b))}});this.tbody.getElements("td").addEvents({click:function(b){b.stop();getSelectionHtml()||"td"!=b.target.get("tag")||(a.editingCell&&a.editingCell!=b.target.getParent()&&a.finishEdit(),a.editingCell||a.startEdit(b.target))},focus:function(b){b.target.hasClass("disabled")?a.currentActive.setFocus().select():(a.currentActive.setProperty("tabindex","-1"),a.currentActive=b.target,b.target.setProperty("tabindex","0"))},keyup:function(b){b.shift&&(a.shift=!1)},keydown:function(b){var c=(b.shift?
"shift-":"")+(b.control?"ctrl-":"")+b.key;["tab","ctrl-enter","enter","esc","f2"].contains(c)&&(b.stop(),a[b.key](b));if(!a.editingCell){var d=!1;"function"==typeOf(a.options.cellKeydown)&&(d=a.options.cellKeydown(b));d||("shift-right right shift-left left shift-up up shift-down down home end pageup pagedown shift-pageup shift-pagedown shift-space ctrl-a shift-f8 delete".split(" ").contains(c)?(b.stop(),a[c](b)):1==c.length&&"td"==b.target.get("tag")&&(a.startEdit(b.target,!1).value=c))}}})},left:function(a){(a=
document.activeElement.getPrevious(":visible:enabled"))&&a.setFocus().select()},right:function(a){(a=document.activeElement.getNext(":visible:enabled"))&&a.setFocus().select()},up:function(a){a=a.target;var b=a.getParent().getPrevious(":visible:enabled");b?(a=b.getElement("td:nth-child("+(a.cellIndex+1)+")"))&&a.setFocus().select():"td"==a.get("tag")&&this.options.sortable&&this.thead.getElement("th:nth-child("+(a.cellIndex+1)+")").setFocus().select()},down:function(a){a=a.target;var b=a.getParent().getNext(":visible:enabled");
b?(a=b.getElement("td:nth-child("+(a.cellIndex+1)+")"))&&a.setFocus().select():"th"==a.get("tag")&&(b=this.tbody.getFirst("tr:visible"))&&(a=b.getElement("td:nth-child("+(a.cellIndex+1)+")"))&&a.setFocus().select()},tab:function(a){a.stop();var b=this.editingCell,c=this.editingCell||a.target;b&&this.finishEdit();if(a.shift){if(a=c.getPrevious("td:visible:enabled"),!a){c=c.getParent().getPrevious("tr:visible:enabled");if(!c)return;a=c.getLast("td:visible:enabled")}}else if(a=c.getNext("td:visible:enabled"),
!a){c=c.getParent().getNext("tr:visible:enabled");if(!c)return;a=c.getFirst("td:visible:enabled")}b?this.startEdit(a):a.setFocus().select()},home:function(a){document.activeElement.getParent().getFirst(":visible:enabled").setFocus().select()},end:function(a){document.activeElement.getParent().getLast(":visible:enabled").setFocus().select()},pageup:function(a){a=a.target;var b=a.getParent().getParent().getFirst(":visible:enabled");b&&(a=b.getElement("td:nth-child("+(a.cellIndex+1)+")"))&&a.setFocus().select()},
pagedown:function(a){a=a.target;var b=a.getParent().getParent().getLast(":visible:enabled");b&&(a=b.getElement("td:nth-child("+(a.cellIndex+1)+")"))&&a.setFocus().select()},"shift-pageup":function(a){a=a.target;var b=a.getParent(),c=b.getParent().getFirst(":visible:enabled"),d=b.getParent().getChildren();for(b=b.rowIndex-1;b>=c.rowIndex-1;b--)d[b].getChildren()[a.cellIndex].select()},"shift-pagedown":function(a){a=a.target;var b=a.getParent(),c=b.getParent().getLast(":visible:enabled"),d=b.getParent().getChildren();
for(b=b.rowIndex;b<=c.rowIndex-1;b++)d[b].getChildren()[a.cellIndex].select()},"shift-space":function(a){this.selection.each(function(a){return a.getSiblings(":visible:enabled").select()})},"shift-left":function(a){this.selection.each(function(a){(a=a.getPrevious(":visible:enabled"))&&a.select()})},"shift-right":function(a){this.selection.each(function(a){(a=a.getNext(":visible:enabled"))&&a.select()})},"shift-up":function(a){this.selection.each(function(a){var b=a.getParent().getPrevious(":visible:enabled");
b&&(a=b.getElement("td:nth-child("+(a.cellIndex+1)+")"),a.hasClass("disabled")||a.select())})},"shift-down":function(a){this.selection.each(function(a){var b=a.getParent().getNext(":visible:enabled");b&&(a=b.getElement("td:nth-child("+(a.cellIndex+1)+")"),a.hasClass("disabled")||a.select())})},"ctrl-space":function(a){var b=this;this.selection.each(function(a){var c=a.cellIndex+1;b.tbody.getElements("tr").each(function(a){return a.getElement("td:nth-child("+c+")").select()})})},"ctrl-a":function(a){this.tbody.getElements("td:visible:enabled").select()},
setFocus:function(a){var b=this;a&&(this.clearSelection(),setTimeout(function(){a.focus();b.focusChanged(a)},0))},focusChanged:function(a){this.previous_tr&&this.previous_tr.removeClass("focus");this.previous_tr=a.getParent();this.previous_tr.addClass("focus")},setSelection:function(a){a&&!a.hasClass("table-td-selected")&&(a.addClass("table-td-selected"),a.setProperty("aria-selected","true"),this.selection?this.selection.push(a):this.selection=[a],1<this.selection.length&&this.multiSelect&&(this.multiSelectActive=
!0))},clearSelection:function(){this.tbody.getElements("td").each(function(a){a.removeClass("table-td-selected");a.setProperty("aria-selected","false")});this.thead.getElements("th").each(function(a){a.removeClass("table-td-selected");a.setProperty("aria-selected","false")});this.multiSelect?(this.shift||(this.multiSelectActive&&(this.multiSelect=this.multiSelectActive=!1),this.selection.empty()),this.selection.addClass("table-td-selected")):this.selection.empty()},enter:function(a){if("th"==a.target.get("tag"))this.headClick(a,
a.target);else if(this.editingCell)a=this.editingCell,this.finishEdit()&&"function"==typeOf(this.options.nextField)&&(a=this.options.nextField(a))&&this.startEdit(a);else{var b=a.target;"td"!=a.target.get("tag")&&(b=b.getParent("td"));b&&this.startEdit(b)}},f2:function(a){this.editingCell||this.startEdit(a.target)},esc:function(a){this.editingCell&&this.cancelEdit()},"delete":function(a){this.selection.each(function(a){return a.setValue(null,!1,!1,!1,!0)})},disableHeader:function(){this.thead.addClass("disabled");
StyleWriter.createStyle("table.ariaGrid th:hover { background-color: #eeeeee }","foo");return this},enableHeader:function(){this.thead.removeClass("disabled");StyleWriter.removeStyle("foo");return this},disableRow:function(a){"number"!=typeof a&&(a=this.tbody.getElement("td:first-child:match("+a+")").getParent("tr").rowIndex);this.tbody.getElements("tr:nth-child("+a+") td").addClass("disabled");return this},enableRow:function(a){"number"!=typeof a&&(a=this.tbody.getElement("td:first-child:match("+
a+")").getParent("tr").rowIndex);this.tbody.getElements("tr:nth-child("+a+") td").removeClass("disabled");return this},hideRow:function(a){"number"!=typeof a&&(a=this.tbody.getElement("td:first-child:match("+a+")").getParent("tr").rowIndex);this.tbody.getElements("tr:nth-child("+a+")").hide();return this},showRow:function(a){"number"!=typeof a&&(a=this.tbody.getElement("td:first-child:match("+a+")").getParent("tr").rowIndex);this.tbody.getElements("tr:nth-child("+a+")").show();return this},isRowDisplayed:function(a){if("number"!=
typeof a){a=this.tbody.getElement("td:first-child:match("+a+")");if(!a)return!1;a=a.getParent("tr").rowIndex}return(a=this.tbody.getElement("tr:nth-child("+a+")"))?a.isDisplayed():!1},columnIndex:function(a){return(a=this.thead.getElement('th:match("'+a+'")'))?a.cellIndex+1:0},disableColumn:function(a){"number"!=typeof a&&(a=(a=this.thead.getElement('th:match("'+a+'")'))?a.cellIndex+1:0);a&&this.element.getElements("th:nth-child("+a+"), td:nth-child("+a+")").addClass("disabled");return this},enableColumn:function(a){"number"!=
typeof a&&(a=(a=this.thead.getElement('th:match("'+a+'")'))?a.cellIndex+1:0);a&&this.element.getElements("th:nth-child("+a+"), td:nth-child("+a+")").removeClass("disabled");return this},hideColumn:function(a){var b=this;"array"==typeOf(a)?a.each(function(a){return b.hideColumn(a)}):("number"!=typeof a&&(a=(a=this.thead.getElement('th:match("'+a+'")'))?a.cellIndex+1:0),a&&this.element.getElements("th:nth-child("+a+"), td:nth-child("+a+")").hide());return this},showColumn:function(a){var b=this;"array"==
typeOf(a)?a.each(function(a){return b.showColumn(a)}):("number"!=typeof a&&(a=(a=this.thead.getElement('th:match("'+a+'")'))?a.cellIndex+1:0),a&&this.element.getElements("th:nth-child("+a+"), td:nth-child("+a+")").show());return this},isColumnDisplayed:function(a){"number"!=typeof a&&(a=(a=this.thead.getElement('th:match("'+a+'")'))?a.cellIndex+1:0);return a?this.element.getElement("th:nth-child("+a+"), td:nth-child("+a+")").isDisplayed():!1},getColumnHeader:function(a){if(a=this.thead.getElement("th:nth-child("+
(a.cellIndex+1)+")"))return a.get("html").replace(/&lt;/g,"<").replace(/&gt;/g,">")},getRowHeader:function(a){return a.getParent("tr").getFirst("td, th").get("html").replace(/&lt;/g,"<").replace(/&gt;/g,">")},setColumnWidth:function(a,b){return this.setColumnStyles(a,{width:b})},setColumnStyles:function(a,b){"number"!=typeof a&&(a=(a=this.thead.getElement('th:match("'+a+'")'))?a.cellIndex+1:0);a&&this.tbody.getElements("th:nth-child("+a+"), td:nth-child("+a+")").setStyles(b);return this},cell:function(a,
b){"number"!=typeof a&&(a=(a=this.tbody.getElement('td:nth-child(1):match("'+a+'")'))?a.getParent().rowIndex:0);"number"!=typeof b&&(b=(b=this.thead.getElement('th:match("'+b+'")'))?b.cellIndex+1:0);if(a&&b)return this.tbody.getElement("tr:nth-child("+a+") td:nth-child("+b+")")},row:function(a){return this.tbody.getElement("tr:nth-child("+a+")")},rowExists:function(a){return!!this.tbody.getElement('td:nth-child(1):match("'+a+'")')},columnExists:function(a){return!!this.thead.getElement('th:match("'+
a+'")')},searchInColumn:function(a,b,c,d){"undefined"==typeof c&&(c=!1);"undefined"==typeof d&&(d=!1);"number"!=typeof a&&(a=(a=this.thead.getElement('th:match("'+a+'")'))?a.cellIndex+1:0);return a?this.tbody.getElements("td:nth-child("+a+'):match("'+b+'")'+(c?":visible":"")+(d?":not(.disabled)":"")):null},countInColumn:function(a,b,c,d){"undefined"==typeof c&&(c=!1);"undefined"==typeof d&&(d=!1);"number"!=typeof a&&(a=(a=this.thead.getElement('th:match("'+a+'")'))?a.cellIndex+1:0);return a?this.tbody.getElements("td:nth-child("+
a+'):match("'+b+'")'+(c?":visible":"")+(d?":not(.disabled)":"")).length:null},setColumnValue:function(a,b,c,d,e){"number"!=typeof a&&(a=(a=this.thead.getElement('th:match("'+a+'")'))?a.cellIndex+1:0);this.tbody.getElements("td:nth-child("+a+")").setValue(b,c,d,e)},getColumnValues:function(a){"number"!=typeof a&&(a=(a=this.thead.getElement('th:match("'+a+'")'))?a.cellIndex+1:0);var b=[];this.tbody.getElements("td:nth-child("+a+")").each(function(a){return b.push(a.get("data"))});return b},getText:function(a,
b){return(a=this.cell(a,b))?a.get("text"):null},getCell:function(a,b){return(a=this.cell(a,b))?a.get("data"):null},setCell:function(a,b,c,d,e,f,g){(a=this.cell(a,b))&&("object"==typeOf(c)?a.set(c):a.setValue(c,d,e,f,g));return this},setTD:function(a,b,c,d,e,f){var g=a.get("data");if(d&&g||e&&a.hasClass("disabled"))return!0;d={isValid:!0};f&&"function"===typeOf(this.options.validator)&&(d=this.options.validator(a,g,b));if("isValid"in d&&!d.isValid)return!1;"value"in d&&(b=d.value);(f=g!=b)&&a.set("data",
b);d=null;"function"==typeOf(this.options.formatter)&&(e=this.options.formatter(a.cellIndex,b,a),"object"==typeOf(e)?(b=e.text,"title"in e&&(d=e.title)):b=e);"function"==typeOf(this.options.cellChanging)&&this.options.cellChanging(a,b);a.set("html",b);a.set("title",d);a.setStyle("padding","");f&&!c&&"function"==typeOf(this.options.cellChanged)&&this.options.cellChanged(a,g);return!0},startEdit:function(a,b){var c=this;if(a&&!a.hasClass("disabled")&&("function"!=typeOf(this.options.isEditable)||this.options.isEditable(a))){"undefined"===
typeof b&&(b=this.options.autoSelect);this.editingCell&&this.finishEdit();this.clearSelection();var d;"function"==typeOf(this.options.getInputElement)&&(d=this.options.getInputElement(a));"undefined"===typeof d&&(d=new Element("input[type=text]",{value:a.get("data")}));if(d){a.setStyle("padding","0").set("html","");var e=a.getHeight();d.setStyles({width:"100%",height:e,"text-align":a.getStyle("text-align")});a.grab(d);d.addEvent("click",function(a){return a.stopPropagation()});setTimeout(function(){d.focus();
b&&d.select();c.focusChanged(a)},10);this.setEditingCell(a);return d}}},finishEdit:function(){if(!this.editingCell)return!0;var a=this.editingCell,b=a.get("data");b=a.getFirst()?a.getFirst().value:b;try{return a.setValue(b,!1,!1,!1,!0),a.setFocus().select(),this.setEditingCell(null),!0}catch(c){return!1}},cancelEdit:function(){var a=this.editingCell,b=a.get("data");if(b=a.setValue(b))a.setFocus().select(),this.setEditingCell(null);return b},setEditingCell:function(a){this.editingCell=a;"function"==
typeOf(this.options.editingmodeChanged)&&this.options.editingmodeChanged(this.editingCell)}});function getSelectionHtml(){var a="";if("undefined"!=typeof window.getSelection){var b=window.getSelection();if(b.rangeCount){a=document.createElement("div");for(var c=0,d=b.rangeCount;c<d;++c)a.appendChild(b.getRangeAt(c).cloneContents());a=a.innerHTML}}else"undefined"!=typeof document.selection&&"Text"==document.selection.type&&(a=document.selection.createRange().htmlText);return a}
function getSelectionText(){var a="";"undefined"!=typeof window.getSelection?a=window.getSelection().toString():"undefined"!=typeof document.selection&&"Text"==document.selection.type&&(a=document.selection.createRange().text);return a};
